### Health Check
GET http://127.0.0.1:8001/health

### Daily Demand Prediction
POST http://127.0.0.1:8001/predict/demand
Content-Type: application/json

{
  "menu_id": 1,
  "menu_name": "Es Kopi Susu",
  "menu_category": "Coffee",
  "is_coffee_based": true,
  "menu_segment": "bestseller",
  "unit_price": 22000,
  "target_date": "2026-05-25"
}

### Stock-out Prediction
POST http://127.0.0.1:8001/predict/stock-out
Content-Type: application/json

{
  "menu_id": 1,
  "menu_name": "Es Kopi Susu",
  "menu_category": "Coffee",
  "is_coffee_based": true,
  "menu_segment": "bestseller",
  "unit_price": 22000,
  "current_stock": 80,
  "start_date": "2026-05-25",
  "forecast_days": 30
}
